### ISSUE TITLE
Special characters in attributes break the decoding

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-WP-Shortcodes-Extension#1]
Steps to reproduce:
1. Activate a WP default theme
2. Add Accordion shortcode
3. Edit shortcode and add 2 tabs with simple text: `hello world`
4. Add another Accordion shortcode
5. Edit shortcode and add 2 tabs with text:
   
   ```
   Test '"\'\"[]{} [test] [test x="y" a=\"b c '" <b>test</b> Привет ĂăÎîȘșȚțÂâ
   ```
6. Edit file: `unyson/framework/extensions/shortcodes/shortcodes/accordion/views/view.php` and add `fw_print($atts);`
7. Open frontend https://static.md/70a5f49e7b0f605bd399b302beb0e7a4.png

---

In PageBuilder [it works](https://static.md/865580c3a565da1536905cc70feb678f.png)

**Comment by andreiglingeanu** [comment]
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/4c2fb06cb6fac2889f6efd3978a2d14e7d798273
It was `=` breaking the party.

<hr>

Now you guys better think about some other way of doing encoding, because it's getting really [bad](https://i.imgur.com/2LvKutS.png).

How to see the actual content before the Aggressive Coder takes in:
1. In the WordPress folder find `wp-includes/default-filters.php`
2. Find line `421` -- `add_filter( 'the_content', 'do_shortcode', 11 ); // AFTER wpautop()`
3. Replace with this to see the actual content:
4. Take the steps from the issue content.

``` php
add_filter( 'the_content', 'my_ct_do_shortcode', 11 ); // AFTER wpautop()

function my_ct_do_shortcode($content) {
    fw_print($content);
    return do_shortcode($content);
}
```

<hr>

Changing encoding involves changing this two arrays:
1. [PHP](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/4c2fb06cb6fac2889f6efd3978a2d14e7d798273/includes/coder/class-fw-ext-shortcodes-attr-coder-aggressive.php#L10)
2. [JS](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/4c2fb06cb6fac2889f6efd3978a2d14e7d798273/static/js/aggressive-coder.js#L2)

**Comment by ghost** [comment]
@andreiglingeanu If you think [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/6f918556f5a11c5a27041ccfea4e96ed7a91fb02) is ok

```
[accordion tabs="‹¡º¡›{‹¡²¡›tab_title‹¡²¡›:‹¡²¡›Test ‹¡³¡›‹¡ª¡›‹¡²¡›‹¡ª¡›‹¡ª¡›‹¡³¡›‹¡ª¡›‹¡ª¡›‹¡ª¡›‹¡²¡›‹¡º¡›‹¡¹¡›{} ‹¡º¡›test‹¡¹¡› ‹¡º¡›test x‹¡´¡›‹¡ª¡›‹¡²¡›y‹¡ª¡›‹¡²¡› a‹¡´¡›‹¡ª¡›‹¡ª¡›‹¡ª¡›‹¡²¡›b c ‹¡³¡›‹¡ª¡›‹¡²¡› <b>test</b>‹¡²¡›,‹¡²¡›tab_content‹¡²¡›:‹¡²¡›Test ‹¡³¡›‹¡ª¡›‹¡²¡›‹¡ª¡›‹¡ª¡›‹¡³¡›‹¡ª¡›‹¡ª¡›‹¡ª¡›‹¡²¡›‹¡º¡›‹¡¹¡›{} ‹¡º¡›test‹¡¹¡› ‹¡º¡›test x‹¡´¡›‹¡ª¡›‹¡²¡›y‹¡ª¡›‹¡²¡› a‹¡´¡›‹¡ª¡›‹¡ª¡›‹¡ª¡›‹¡²¡›b c ‹¡³¡›‹¡ª¡›‹¡²¡› <b>test</b>‹¡²¡›}‹¡¹¡›" __fw_editor_shortcodes_id="96f191c6ebb3d8100fe39222a44908c5" _array_keys="{‹¡²¡›tabs‹¡²¡›:‹¡²¡›tabs‹¡²¡›}" _fw_coder="aggressive"][/accordion]
```

please merge [this branch](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/compare/extended-ascii)

**Comment by ghost** [comment]
#### Hardcore test
1. Activate a default WP theme
2. Set [here](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/v1.3.17/shortcodes/accordion/options.php#L18) `wp-editor`
3. Add new post and add an Accordion shortcode in editor
4. Open this page http://www.ascii-code.com/
5. `Ctrl+A` (Select All) then `Ctrl+C` (Copy)
6. Paste in wp-editor visual mode
7. Update post
8. Check frontend
9. Switch post editor to text mode then back to visual mode
